# Конфиг golangci-lint — можно ужесточать по мере необходимости
run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
  disable:
    - unused # helpers для будущих фич

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  staticcheck:
    checks: ["-S1001"] # цикл с model.Photo трансформирует, copy() не подходит
