# Конфиг golangci-lint — можно ужесточать по мере необходимости
run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
