# Конфиг golangci-lint — можно ужесточать по мере необходимости
run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
  disable:
    - unused # helpers для будущих фич

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (*go.mongodb.org/mongo-driver/mongo.Cursor).Close
