// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
	"github.com/cnpf/feeder-backend/graph/scalars"
)

type AuthResult struct {
	Ok    bool    `json:"ok"`
	Token *string `json:"token,omitempty"`
}

type Author struct {
	ID        string  `json:"id"`
	Username  string  `json:"username"`
	HasAvatar bool    `json:"hasAvatar"`
	AvatarURL *string `json:"avatarUrl,omitempty"`
}

type ChatResponse struct {
	Message string        `json:"message"`
	Results []*ChatResult `json:"results"`
}

type ChatResult struct {
	ID          string  `json:"id"`
	Type        string  `json:"type"`
	Title       string  `json:"title"`
	HasPhotos   bool    `json:"hasPhotos"`
	PhotosCount int     `json:"photosCount"`
	Location    *string `json:"location,omitempty"`
}

type Coach struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type CoachInput struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type Competition struct {
	ID               string        `json:"id"`
	Title            string        `json:"title"`
	StartDate        scalars.Time  `json:"startDate"`
	EndDate          scalars.Time  `json:"endDate"`
	Location         string        `json:"location"`
	Tours            []*Tour       `json:"tours"`
	OpeningDate      *scalars.Time `json:"openingDate,omitempty"`
	OpeningTime      *string       `json:"openingTime,omitempty"`
	IndividualFormat bool          `json:"individualFormat"`
	TeamFormat       bool          `json:"teamFormat"`
	Fee              *float64      `json:"fee,omitempty"`
	TeamLimit        *int          `json:"teamLimit,omitempty"`
	Regulations      *string       `json:"regulations,omitempty"`
	CreatedAt        *scalars.Time `json:"createdAt,omitempty"`
	UpdatedAt        *scalars.Time `json:"updatedAt,omitempty"`
}

type CompetitionInput struct {
	Title            string       `json:"title"`
	StartDate        string       `json:"startDate"`
	EndDate          string       `json:"endDate"`
	Location         string       `json:"location"`
	Tours            []*TourInput `json:"tours"`
	OpeningDate      *string      `json:"openingDate,omitempty"`
	OpeningTime      *string      `json:"openingTime,omitempty"`
	IndividualFormat bool         `json:"individualFormat"`
	TeamFormat       bool         `json:"teamFormat"`
	Fee              *string      `json:"fee,omitempty"`
	TeamLimit        *string      `json:"teamLimit,omitempty"`
	Regulations      *string      `json:"regulations,omitempty"`
}

type CreateRegistrationInput struct {
	CompetitionID string              `json:"competitionId"`
	Type          string              `json:"type"`
	TeamName      *string             `json:"teamName,omitempty"`
	Participants  []*ParticipantInput `json:"participants"`
	Coach         *CoachInput         `json:"coach,omitempty"`
}

type CreateReportInput struct {
	Title  string            `json:"title"`
	Text   string            `json:"text"`
	Photos []*graphql.Upload `json:"photos,omitempty"`
}

type LoginInput struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Participant struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type ParticipantInput struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type Photo struct {
	URL string `json:"url"`
}

type Query struct {
}

type RegisterInput struct {
	Email           string          `json:"email"`
	Username        string          `json:"username"`
	Password        string          `json:"password"`
	PasswordConfirm string          `json:"passwordConfirm"`
	Avatar          *graphql.Upload `json:"avatar,omitempty"`
}

type Registration struct {
	ID            string         `json:"id"`
	CompetitionID string         `json:"competitionId"`
	UserID        string         `json:"userId"`
	Type          string         `json:"type"`
	TeamName      *string        `json:"teamName,omitempty"`
	Participants  []*Participant `json:"participants"`
	Coach         *Coach         `json:"coach,omitempty"`
	CanEdit       bool           `json:"canEdit"`
	CreatedAt     scalars.Time   `json:"createdAt"`
	UpdatedAt     scalars.Time   `json:"updatedAt"`
}

type Report struct {
	ID        string        `json:"id"`
	Title     string        `json:"title"`
	Text      string        `json:"text"`
	CreatedAt *scalars.Time `json:"createdAt,omitempty"`
	UpdatedAt *scalars.Time `json:"updatedAt,omitempty"`
	AuthorID  string        `json:"authorId"`
	Author    *Author       `json:"author"`
	Photos    []*Photo      `json:"photos"`
	CanEdit   bool          `json:"canEdit"`
}

type Tour struct {
	Date scalars.Time `json:"date"`
	Time string       `json:"time"`
}

type TourInput struct {
	Date string `json:"date"`
	Time string `json:"time"`
}

type UpdateProfileInput struct {
	Username     *string         `json:"username,omitempty"`
	RemoveAvatar *bool           `json:"removeAvatar,omitempty"`
	Avatar       *graphql.Upload `json:"avatar,omitempty"`
}

type UpdateRegistrationInput struct {
	TeamName     *string             `json:"teamName,omitempty"`
	Participants []*ParticipantInput `json:"participants"`
	Coach        *CoachInput         `json:"coach,omitempty"`
}

type UpdateReportInput struct {
	Title           *string           `json:"title,omitempty"`
	Text            *string           `json:"text,omitempty"`
	RemovePhoto     []int             `json:"removePhoto,omitempty"`
	RemoveAllPhotos *bool             `json:"removeAllPhotos,omitempty"`
	Photos          []*graphql.Upload `json:"photos,omitempty"`
}

type User struct {
	ID        string  `json:"id"`
	Email     string  `json:"email"`
	Username  string  `json:"username"`
	IsAdmin   bool    `json:"isAdmin"`
	HasAvatar bool    `json:"hasAvatar"`
	AvatarURL *string `json:"avatarUrl,omitempty"`
}
